"""added new cycle

Revision ID: 09b91c46112d
Revises: dfc59779a5e0
Create Date: 2025-03-04 19:35:33.693810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b91c46112d'
down_revision = 'dfc59779a5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle_monitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_days', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('cycle_length', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle_monitor', schema=None) as batch_op:
        batch_op.drop_column('cycle_length')
        batch_op.drop_column('period_days')

    # ### end Alembic commands ###
