"""empty message

Revision ID: 12b4f43542e1
Revises: fdd8bab53f0e
Create Date: 2025-03-05 19:57:19.338732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b4f43542e1'
down_revision = 'fdd8bab53f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menstrual_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_menstruation', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('meal_plan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('goal', sa.VARCHAR(length=50), nullable=False),
    sa.Column('diet', sa.VARCHAR(length=50), nullable=False),
    sa.Column('veg_nonveg', sa.VARCHAR(length=50), nullable=False),
    sa.Column('allergies', sa.VARCHAR(length=200), nullable=True),
    sa.Column('breakfast', sa.VARCHAR(length=255), nullable=False),
    sa.Column('lunch', sa.VARCHAR(length=255), nullable=False),
    sa.Column('dinner', sa.VARCHAR(length=255), nullable=False),
    sa.Column('snacks', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('menstrual_cycle')
    # ### end Alembic commands ###
