"""added new

Revision ID: 592c253b01b0
Revises: 0f7c7a0afadb
Create Date: 2025-03-04 16:11:13.813122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592c253b01b0'
down_revision = '0f7c7a0afadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_date', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('added_time', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_reminder', schema=None) as batch_op:
        batch_op.drop_column('added_time')
        batch_op.drop_column('added_date')

    # ### end Alembic commands ###
