"""added new cycle history

Revision ID: 7a12a251ec08
Revises: 09b91c46112d
Create Date: 2025-03-04 20:15:13.107273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a12a251ec08'
down_revision = '09b91c46112d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle_monitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('period_days')
        batch_op.drop_column('cycle_length')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle_monitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_length', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
        batch_op.add_column(sa.Column('period_days', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
