"""empty message

Revision ID: 947d1d458db4
Revises: 12b4f43542e1
Create Date: 2025-03-05 20:03:47.591816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947d1d458db4'
down_revision = '12b4f43542e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menstrual_cycle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menstrual_cycle',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('last_menstruation', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###
